# A github workflow that make sure the PR passes linting

name: PR Validation

on:
  pull_request:
    branches:
      - main

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20.9.0'
      - name: Install dependencies
        run: npm install
      - name: Lint
        run: npm run lint